name: 'Structuresoftheworld '
favicon: null
layout_spectrum: 0.00445
typography_spectrum: 0.65438
title: Structures of the World
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1F1726'
    - '#0E909B'
    - '#1F4B5B'
    - '#5C3127'
    - '#B4A388'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
