layout_spectrum: 0.4978518
color:
  saturation: 0.7556391
  brandStrength: 0.3163418
  lightness: 1
  rhythmicContrast: 0.5032223
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.9017185
name: 'Structuresoftheworld '
