title: Structures of the World
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 1
  lightness: 0.9940923
  brandColors:
    - '#FCFDFF'
    - '#414142'
    - '#86878A'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: 'Structuresoftheworld '
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1756176
layout_spectrum: 0.04672394
