name: 'Structuresoftheworld '
favicon: null
layout_spectrum: 0.4978518
typography_spectrum: 0.9017185
title: Structures of the World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3163418
  lightness: 1
  saturation: 0.7556391
  rhythmicContrast: 0.5032223
purpose: []
